name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Organization introduction
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/metrics.plugin.introduction.svg
          user: dawntech
          base: header
          plugin_introduction: yes
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dawntech
          filename: profile/languages.svg
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
      - name: Dawntech YouTube RSS
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.plugin.rss.svg
          base: ""
          token: NOT_NEEDED
          plugin_rss: yes
          plugin_rss_source: https://www.youtube.com/feeds/videos.xml?channel_id=UCX_dAlOJYox73_CPm-S7RSw
          plugin_rss_limit: 4
